name: Android CI (use system gradle)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Install Gradle (system)
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle

      - name: Make gradlew executable if present
        run: |
          if [ -f ./gradlew ]; then chmod +x ./gradlew; fi

      - name: Run assembleDebug (system gradle)
        working-directory: .
        run: |
          gradle assembleDebug --no-daemon
